---
title: "Roystonea"
author: "Jorge Alonso"
date: "2026-05-30"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show
    self_contained: true
---

# 1. Preparing for analysis

## 1.1. Loading data and packages

```{r}
# Loading packages
library(tidyverse)
library(DHARMa)
library(car)
library(lmtest)
library(MASS)
library(lme4)
library(lmerTest)
library(performance)
library(emmeans)
```

```{r}
# Limpeza do histórico e da memória
rm(list=ls(all=TRUE)) 
gc() 
```

```{r}
# Database link
processed_url <- "https://raw.githubusercontent.com/jmalonso55/Applied-Statistics-for-a-Tropical-Arboretum/refs/heads/main/data/processed_data.csv"
```


```{r}
# Loading data
data_trab <- read.csv(processed_url, sep = ",")

# Checking
summary(data_trab)
```

## 1.2. Filtering database

```{r}
# Filtering for Arecaceae
palmeira <- data_trab %>% 
  filter(family == "Arecaceae")
```


```{r}
# Filtering for Roystonea
roystonea <- palmeira %>% 
  filter(genus == "Roystonea", !is.na(species))
```


```{r}
# Identificar canteiros com mais de 3 indivíduos
canteiros_n3 <- roystonea %>%
  count(sec_cant) %>%
  filter(n > 3) %>%
  pull(sec_cant)

# Base filtrada
roystonea_n3 <- roystonea %>%
  filter(sec_cant %in% canteiros_n3) %>% 
  mutate(species == factor(species), sec_cant = factor(sec_cant))
```


```{r}
ggplot(roystonea_n3, aes(x = dap, y = altura, color = species)) +
  geom_point()
```

# 2. Regression analysis

## 2.1. Fixed effects

### 2.1.1. Linear model

```{r}
# Linear model
mod1 <- lm(altura ~ dap + species, data = roystonea_n3)
```

```{r}
# Analysis of residuals
res_mod1 <- simulateResiduals(mod1, n = 1000)
plot(res_mod1)
```

### 2.1.2. Log model


```{r}
# Log model
mod_log <- lm(altura ~ log(dap) + species, data = roystonea_n3)
```

```{r}
# Analysis of residuals
res_mod_log <- simulateResiduals(mod_log, n = 1000)
plot(res_mod_log)
```

### 2.1.3. Quadratic model

```{r}
# Quadratic model
mod2 <- lm(altura ~ (dap + I(dap^2)) + species, data = roystonea_n3)
```


```{r}
# Analysis of residuals
res_mod2 <- simulateResiduals(mod2, n = 1000)
plot(res_mod2)
```

```{r}
# ANOVA for comparing linear and quadratic regression models
anova(mod1, mod2)
```


### 2.1.4. Quadratic with interaction

```{r}
# Quadratic model
mod2_int <- lm(altura ~ species * (dap +  I(dap^2)), data = roystonea_n3)
```


```{r}
# Analysis of residuals
res_mod2_int <- simulateResiduals(mod2_int, n = 1000)
plot(res_mod2_int)
```

```{r}
# Comparing model with and without interaction
anova(mod2, mod2_int)
```

```{r}
# Interaction model summary
summary(mod2_int)
```

```{r}
# Interaction model ANOVA
anova(mod2_int)
```

### 2.1.5. Analysis results

```{r, warning=FALSE, message=FALSE}
# Means comparison between species
emm_sp2 <- emmeans(mod2_int, ~ species, at = list(dap = mean(roystonea_n3$dap, na.rm = TRUE)))

# Multicomparison
multcomp::cld(emm_sp2, adjust = "sidak", Letters = letters)
```

```{r}
# Predicting for graphic
pred_sp <- expand.grid(
  dap = seq(min(roystonea_n3$dap, na.rm = TRUE),
            max(roystonea_n3$dap, na.rm = TRUE),
            length.out = 100),
  species = unique(roystonea_n3$species)
)

pred_sp$altura_pred <- predict(mod2_int, newdata = pred_sp)
```


```{r}
# Graphic with curves within species
ggplot(roystonea_n3, aes(dap, altura, color = species)) +
  geom_point(alpha = 0.6) +
  geom_line(data = pred_sp, aes(y = altura_pred), linewidth = 1.2) +
  labs(x = "DBH (cm)", y = "Height (m)", color = "Species") +
  theme_bw()
```


## 2.2. Mixed effects model

### 2.1.1. Linear model

```{r}
# Mixed effects linear model
mod1m <- lmer(altura ~ dap + species + (1 | sec_cant), data = roystonea_n3, REML = F)
```


```{r}
# Analysis of residuals
res_mod1m <- simulateResiduals(mod1m, n = 1000)
plot(res_mod1m)
```

### 2.1.2. Quadratic model

```{r}
# Mixed effects quadratic model
mod2m <- lmer(altura ~ species + (dap + I(dap^2)) + (1 | sec_cant), data = roystonea_n3, REML = F, control = lmerControl(check.scaleX = "ignore"))
```


```{r}
# Analysis of residuals
res_mod2m <- simulateResiduals(mod2m, n = 1000)
plot(res_mod2m)
testUniformity(res_mod2m)
testDispersion(res_mod2m)
testOutliers(res_mod2m)
```

```{r}
# Understanding the residues

## Residuals versus fitted values
plotResiduals(res_mod2m, roystonea_n3$dap)

## Residuals versus fixed effects
plotResiduals(res_mod2m, roystonea_n3$especie)

## Residuals versus random effects
plotResiduals(res_mod2m, roystonea_n3$sec_cant)
```

### 2.1.3. Comparing models

```{r}
# ANOVA for comparing regression models
anova(mod1m, mod2m)
```

```{r}
# AIC and BIC of fixed and mixed linear and quadratic models
AIC(mod1, mod2, mod2_int, mod1m, mod2m)
BIC(mod1, mod2, mod2_int, mod1m, mod2m)
```


### 2.1.4. Filtering influent observations

```{r}
## Model diagnostics
roystonea_diag <- roystonea_n3 %>%
  mutate(fitted = fitted(mod1m),
    resid = residuals(mod1m),
    resid_stud = rstudent(mod1m),
    cooks = cooks.distance(mod1m),
    leverage = hatvalues(mod1m),
    out_resid = abs(resid_stud) > 3,
    out_cook = cooks > 0.15,
    out_influente = out_resid | out_cook)

## Possibly influent observations
roystonea_influentes <- roystonea_diag %>%
  filter(out_influente) %>%
  arrange(desc(abs(resid_stud))) %>%
  dplyr::select(tombo, altura, dap, fitted, resid, resid_stud, cooks, leverage, out_resid, out_cook)

## Filtered database
roystonea_filtrada <- roystonea_diag %>%
  filter(!out_influente)
```

### 2.1.5. Readjusting the quadratic model


```{r}
# Mixed effects quadratic model
mod2m_f <- lmer(altura ~ species + (dap + I(dap^2)) + (1 | sec_cant), data = roystonea_filtrada, REML = T, control = lmerControl(check.scaleX = "ignore"))
```


```{r}
# Analysis of residuals
res_mod2m_f <- simulateResiduals(mod2m_f, n = 1000)
plot(res_mod2m_f)
testUniformity(res_mod2m_f)
testDispersion(res_mod2m_f)
testOutliers(res_mod2m_f)
```

```{r}
# Checking multicollinearity
vif(mod2m_f)
```


```{r}
# Model summary
summary(mod2m_f)
```

```{r}
# Model ANOVA
anova(mod2m_f)
```

```{r}
# Testing the significance of random effects
ranova(mod2m_f)
```


```{r}
# Variance explained by random effects
icc(mod2m_f)
```


```{r}
# Model adjusted R²
r2(mod2m_f)
```


```{r}
# Means comparison between species
emm_sp <- emmeans(mod2m_f, ~ species)

multcomp::cld(emm_sp, adjust = "sidak", Letters = letters)
```

# 3. Results visualization

```{r}
# Random effects of arboretum beds
efeito_cant <- ranef(mod2m_f)$sec_cant %>%
  as.data.frame() %>%
  rownames_to_column("sec_cant") %>%
  rename(efeito_canteiro = `(Intercept)`)

# DBH sequence for prediction
dap_seq <- seq(min(roystonea_filtrada$dap, na.rm = TRUE), max(roystonea_filtrada$dap, na.rm = TRUE), length.out = 300)
```

```{r}
# Marginal global mean curve across species
pred_global <- crossing(dap = dap_seq, species = unique(roystonea_filtrada$species)) %>%
  mutate(altura_pred = predict(mod2m_f, newdata = ., re.form = NA)) %>%
  summarise(altura_pred = mean(altura_pred, na.rm = TRUE), .by = dap)
```


```{r}
# Predicted curves by arboretum bed, using only observed DBH range and species in each bed
pred_cant <- roystonea_filtrada %>%
  group_by(sec_cant) %>%
  group_modify(~ crossing(
    dap = seq(
      min(.x$dap, na.rm = TRUE),
      max(.x$dap, na.rm = TRUE),
      length.out = 300),
    species = unique(.x$species))) %>%
  ungroup() %>%
  mutate(altura_pred = predict(mod2m_f, newdata = ., re.form = NULL)
  ) %>%
  summarise(altura_pred = mean(altura_pred, na.rm = TRUE), .by = c(dap, sec_cant)) %>%
  left_join(efeito_cant, by = "sec_cant")
```


```{r}
# Color palette ordered by random-effect value
efeito_ord <- pred_cant %>%
  distinct(sec_cant, efeito_canteiro) %>%
  arrange(efeito_canteiro)

cores_cant <- setNames(colorRampPalette(c("#F4A6A6", "#F6C27A", "#F7E58B", "#8EDFE3", "#9BB7E8"))(nrow(efeito_ord)), efeito_ord$sec_cant)

labels_cant <- setNames( paste0(efeito_ord$sec_cant, " (", round(efeito_ord$efeito_canteiro, 2), ")"), efeito_ord$sec_cant)
```


```{r}
# Plot with points by species, curves by planting bed, and global mean curve
ggplot(roystonea_filtrada, aes(dap, altura)) +
  geom_point(aes(shape = species), alpha = 0.4, size = 1) +
  geom_line(data = pred_cant, aes(y = altura_pred, group = sec_cant, color = sec_cant), linewidth = 0.6, alpha = 0.8) +
  geom_line(data = pred_global, aes(x = dap, y = altura_pred), inherit.aes = FALSE, linewidth = 1.3, alpha = 0.7, color = "gray30") +
  scale_color_manual(values = cores_cant, breaks = efeito_ord$sec_cant, labels = labels_cant, name = "Arboretum bed\n(random effect)") +
  labs(x = "DBH (cm)", y = "Height (m)", shape = "Species") +  
  theme_classic()
```
